config/routes.rb
Rails.application.routes.draw do
  root to: "mangas#index"
  resources :mangas
  resources :volumes
  resources :genres
  # get "/volumes/:id", to: "volumes#show", as: "volume"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :mangas_genres
    has_many :mangas, through: :mangas_genres
end

app/models/manga.rb
class Manga < ApplicationRecord
  belongs_to :volume
  has_many :mangas_genres
  has_many :genres, through: :mangas_genres

  def list_genres
    self.genres.map {|genre| genre.name}.join (', ')
  end
  
end

app/models/mangas_genre.rb
class MangasGenre < ApplicationRecord
  belongs_to :manga
  belongs_to :genre
end

app/models/volume.rb
class Volume < ApplicationRecord
    has_many :mangas

    def version
        return "#{edition}"
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
    before_action :set_genre, only: [:show]
    before_action :read_genres, only: [:index]
    def index
    end

    def show 
    end

    private
    def read_genres
        @genres = Genre.all
    end
    def set_genre
        if params[:id]
            @genre = Genre.find(params[:id])
        end
    end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
    before_action :read_mangas, only: [:index]
    before_action :set_manga, only: [:show]

    def index
    end

    def show
    end

    private
    def read_mangas
       @mangas = Manga.all
    end
    def set_manga
        if params[:id]
            @manga = Manga.find(params[:id])
        end
    end
end

app/controllers/volumes_controller.rb
class VolumesController < ApplicationController
    before_action :set_volume, only: [:show]
    def show
    end

    private 
    def set_volume
        if params[:id]
            @volume = Volume.find(params[:id])
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/volumes_helper.rb
module VolumesHelper
end

app/views/genres/index.html.erb
<%@genres.each do |genre|%>
    <p><%=link_to genre.name, genre_path(genre.id)%></p>
<%end%>

app/views/genres/show.html.erb
<section class="card">
    <h1><%=@genre.name%></h1>
    <% @genre.mangas.each do |manga|%>
    <%=link_to manga.title, manga_path(manga.id)%>
    <%end%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MangaStore</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <section class="section">
        <section class="content">
          <%=render "shared/nav"%>
          <%= yield %>
        </section>
      </section>
  </body>
</html>

app/views/mangas/_manga.html.erb
<section class="card">
    <h1><%=manga.title%></h1>
    <p>Volume: <%=manga.volume.version%></p>
    <p>Genres: <%=link_to manga.list_genres%></p>
</section>

app/views/mangas/index.html.erb
<h1>MangaStore</h1>
<% @mangas.each do |manga|%>
    <p><%=link_to manga.title, manga_path(manga.id)%></p>
<%end%>

app/views/mangas/show.html.erb
<%= render partial: "manga", locals: {manga: @manga}%>

app/views/shared/_nav.html.erb
<nav class="content">
    <%=link_to "Mangas", mangas_path, class: "has-background-danger has-text-light p-2"%>
    <%=link_to "Genres", genres_path, class: "has-background-dark has-text-light p-2"%>
    <%=link_to "Add Manga", new_manga_path, class: "has-background-dark has-text-light p-2"%>
</nav>

app/views/volumes/show.html.erb
<h1><%=@volume.version%></h1>
<h2>Volume:</h2>
<% @volume.mangas.each do |manga|%>
    <%=link_to manga.title, manga_path(manga.id)%>
<%end%>